#!/bin/bash
#
# SLURM queue script generated by mcsub

#SBATCH --job-name=McXtrace_GPU_%j
#SBATCH --error=TestSuite_GPU_%j.err
#SBATCH --output=TestSuite_GPU_%j.out
#SBATCH --nodes 1
#SBATCH --partition=mesonet
#SBATCH --gres=gpu:1
#SBATCH --ntasks=1
#SBATCH --time 01:00:00
#SBATCH --account m26216

export DATE=`date +%F`

export MAMBA_EXE='/projects/m26216/INSTALL/bin/micromamba';
export MAMBA_ROOT_PREFIX='/projects/m26216/INSTALL/micromamba/';
eval "$("$MAMBA_EXE" shell hook --shell bash --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
micromamba activate panraid
spack load cuda@12.6.2
spack load nvhpc@25.7

mxtest --ncount=1e7 --verbose --openacc --compilemax=1200 --runmax=600 --instr=SOLEIL

### END of McSub script


