/*******************************************************************************
*
* McStas, neutron ray-tracing package
*         Copyright 1997-2002, All rights reserved
*         Risoe National Laboratory, Roskilde, Denmark
*         Institut Laue Langevin, Grenoble, France
*
* Component: Tslit
*
* %I
* Written by: Kim Lefmann and Henrik M. Roennow
* Date: June 16, 1997
* Origin: Risoe
*
* Rectangular/circular slit
*
* %D
* A simple rectangular or circular slit. You may either
* specify the radius (circular shape), or the rectangular bounds.
* No transmission around the slit is allowed.
*
* Example: Slit(xmin=-0.01, xmax=0.01, ymin=-0.01, ymax=0.01)
*          Slit(xwidth=0.02, yheight=0.02)
*          Slit(radius=0.01)
*
* The Slit will issue a warning if run as "closed"
* 
* %P
* INPUT PARAMETERS
*
* radius: [m]   Radius of slit in the z=0 plane, centered at Origo 
* xmin: [m]     Lower x bound 
* xmax: [m]     Upper x bound 
* ymin: [m]     Lower y bound 
* ymax: [m]     Upper y bound 
* xwidth: [m]   Width of slit. Overrides xmin,xmax if they are unset. 
* yheight: [m]  Height of slit. Overrides ymin,ymax if they are unset. 
*
* *
* %E
*******************************************************************************/


DEFINE COMPONENT Tslit
DEFINITION PARAMETERS ()
  SETTING PARAMETERS (x01=-0.60192, x02=0.60192, y01=-0.17138, y02=0.17974,
                      x11=-0.40546, x12=0.39710, y11=-0.38874, y12=0.39710,
                      x21=-0.20482, x22=0.19646, y21=-0.48906, y22=0.49742)
OUTPUT PARAMETERS ()
/* Neutron parameters: (x,y,z,vx,vy,vz,t,sx,sy,sz,p) */
INITIALIZE
%{
%}

TRACE
%{
    PROP_Z0;
    if ( (x>x01 && x<x02 && y>y01 && y<y02) ||
         (x>x11 && x<x12 && y>y11 && y<y12) ||
         (x>x21 && x<x22 && y>y21 && y<y22)   )
       SCATTER ;
    else
       ABSORB;
%}

MCDISPLAY
%{
%}

END
